# =========================
# Builder Stage
# =========================

FROM node:24-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# =========================
# Runtime Stage
# =========================

FROM nginx:alpine

# Copy built frontend
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy custom nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Create non-root user
RUN addgroup -S nginxgroup && adduser -S nginxuser -G nginxgroup

# Create required nginx directories
RUN mkdir -p /var/cache/nginx/client_temp \
    && mkdir -p /var/run/nginx

# Fix permissions
RUN mkdir -p /var/cache/nginx/client_temp \
    && mkdir -p /var/run/nginx \
    && touch /run/nginx.pid \
    && chown -R nginxuser:nginxgroup /var/cache/nginx \
    && chown -R nginxuser:nginxgroup /var/run \
    && chown -R nginxuser:nginxgroup /var/log/nginx \
    && chown -R nginxuser:nginxgroup /usr/share/nginx/html \
    && chown nginxuser:nginxgroup /run/nginx.pid

# Switch to non-root user
USER nginxuser

# Use non-privileged port
EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]